### ISSUE TITLE
Fixes for v2 of the preso

### ISSUE THREAD

**Issue by mcy** [fowles/unleashing-protobuf-evolution#1]
- My name is misspelled in the Protoscope slides.
- Should include a link to Protoscope in the slides.
- Protoscope examples should have line numbers. The `1:` looks like a line number but isn't.
- Slide 2.7 has a broken image link.
- Slide 2.6 should maybe strikethrough the `=2` field instead of deleting it.
- In slide 4.3, mention that there was never a proto2->3 migration plan.

Will mail a CL with fixes shortly.

**Comment by fowles** [comment]
fixed everything except the images

**Comment by fowles** [comment]
fixed
